// Export all canvas functions
export {
  createCanvas,
  addObject,
  moveObject,
  deleteObject,
  pan,
  zoom,
  updateViewport,
  getVisibleCount,
  getVisibleObjectId,
  getVisibleObjectAssetId,
  getVisibleObjectType,
  getTransformX,
  getTransformY,
  getTransformWidth,
  getTransformHeight,
  getTransformRotation,
  undo,
  redo,
  setGridSnap,
  setGridSize,
  getCameraX,
  getCameraY,
  getCameraZoom,
  getGridSize,
  getCanvasWidth,
  getCanvasHeight,
  updateCanvasSize
} from './canvas-manager';
